# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b13fae11db783c1814989866661fb1fbfca2d4fb1ac42d43684a662f24e1d81adf1246358c7de0bc2f6af565807b8248e01a7a9be50531f1f25feddf033569

test:
  secret_key_base: 0e4de3f7b72a0426b75d96a2f1fcc058917e321a1fd54617f8effdb60b41ffa5d8d5e249fbcc03304370f77c1d31ef521335369e932357ba00ca73250ad01c68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
